version: '3.7'

services:
 
  app:
    image: some-image
    links:
      - redis-sentinel
     
  redis-master:
    image: redis:6-alpine
    volumes:
      - "./.data:/data"
    ports:
      - "6379:6379"
 
  redis-slave:
    image: redis:6-alpine
    command: redis-server --slaveof redis-master 6379
    links:
      - redis-master
    volumes:
      - "./.data:/data"
     
  # Instance 1
  redis-sentinel:
    build: 
      context: ./redis-sentinel
    links:
      - redis-master
 
  # Instance 2
  redis-sentinel2:
    build: 
      context: ./redis-sentinel
    links:
      - redis-master
 
  # Instance 3
  redis-sentinel3:
    build: 
      context: ./redis-sentinel
    links:
      - redis-master
